package com.example.e2e4_test_work

const val DEFAULT_INTERVAL_IN_MILLISECONDS = 1000L
const val DEFAULT_MAX_WAIT_TIME = DEFAULT_INTERVAL_IN_MILLISECONDS * 5
const val DEFAULT_LOCATION = "55.751244,37.618423"
const val LAYER_ID = "LAYER_ID"
const val SOURCE_ID = "SOURCE_ID"
const val ICON_ID = "ICON_ID"